name: Just Build index.html

on:
  workflow_dispatch:  # Manual trigger from the Actions tab

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Java 11+
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run the compile .bat file
        run: .\CompileLatestClient.bat

      - name: Move index.html to output folder
        run: |
          mkdir output
          copy build\index.html output\index.html

      - name: Show build folder contents (debugging)
        run: dir /s
