name: Headless Build index.html

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Java 11+
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Initialize workspace
        run: .\build_init.bat

      - name: Compile headless (no GUI)
        run: java -cp "buildtools/BuildTools.jar" net.lax1dude.eaglercraft.v1_8.buildtools.cli.CompileLatestClient

      - name: Prepare output folder
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force output -ErrorAction Ignore
          New-Item -ItemType Directory -Path output
          Copy-Item -Path build\index.html -Destination output\index.html

      - name: Upload index.html as artifact
        uses: actions/upload-artifact@v3
        with:
          name: index-html
          path: output/index.html
