name: Headless Build index.html

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Java 11+
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Initialize workspace
        run: .\build_init.bat

      - name: Compile headless (no GUI)
        run: java -cp "buildtools/BuildTools.jar" net.lax1dude.eaglercraft.v1_8.buildtools.cli.CompileLatestClient

      - name: Collect generated index.html
        run: |
          mkdir output
          copy build\index.html output\index.html

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: index-html
          path: output/index.html
